// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Viora.Infrastructure.Persistence;

#nullable disable

namespace Viora.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724090000_AddCallSessions")]
    partial class AddCallSessions
    {
    }
}
